# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfb4c3059762397ed2149f313541af4bad66e137e73e310483e7b71e60281c8ab86edee31188b6a36f6a65fa11d63ab1fc6b301215b0df731a13763d9ef7cefe

test:
  secret_key_base: 15802b111f3149ccbfbbe2f7c196c2c7e35de4e28782871e851824e44e2370311046afe3420d756dae45de783bd7d6cbd18a860d17a783af051c105b4d533b17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
